# Generated by Django 5.2 on 2025-04-26 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_question', models.PositiveIntegerField()),
                ('correct', models.PositiveIntegerField()),
                ('failed', models.PositiveIntegerField(editable=False)),
                ('score', models.FloatField(editable=False)),
                ('percent', models.FloatField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
