# Generated by Django 5.2 on 2025-05-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
