# Generated by Django 5.2 on 2025-04-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0002_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('choice_a', models.CharField(max_length=255)),
                ('choice_b', models.CharField(max_length=255)),
                ('choice_c', models.CharField(blank=True, max_length=255, null=True)),
                ('choice_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_choices', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
