# Generated by Django 5.2 on 2025-05-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0004_contact_course_faq_subject_teacher_topic_quizsession_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
